# 项目启动端口
server:
  address: 192.168.1.156:5700
  # debug模式
  model: debug
  # release模式
  #model:release /true/false
  enableSwagger: true

# 数据库配置
db:
  dialects: mysql
  host: 192.168.1.156
  port: 3307
  db: devops
  username: root
  password: devops@2025
  charset: utf8
  # 最大空闲数
  maxIdle: 50
  # 最大连接数
  maxOpen: 150

# redis配置
redis:
#  address: 127.0.0.1:6379
  address: 192.168.1.156:6379
  password: "devops@2025"

# 图片地址和ip
imageSettings:
  # 本地磁盘地址
  uploadDir: ./upload/
  # 生产环境域名地址（为空时自动使用当前请求的Host）
  imageHost: "http://10.7.16.22:8080"

# log日志配置
log:
  path: ./log
  name: sys
  # 输出到控制台
  model: console
  # 输出到文件
  # model: file

# 监控配置
monitor:
  prometheus:
    url: "http://192.168.1.227:30901"
  pushgateway:
    url: "http://192.168.1.1:9091"
  agent:
    heartbeat_server_url: "http://192.168.1.156:5700/api/v1/monitor/agent/heartbeat"
    heartbeat_token: "agent-heartbeat-token-2024"
